import { db } from "../server/db";
import { questions } from "../shared/schema";

const extraQuestions = [
  // More football questions to reach 2000
  { questionText: "Which player has the most Premier League assists?", optionA: "Frank Lampard", optionB: "Ryan Giggs", optionC: "Kevin De Bruyne", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Who is the youngest Premier League captain ever?", optionA: "Wayne Rooney", optionB: "Harry Kane", optionC: "Fabregas was 21", correctAnswer: "C", difficulty: "hard" },
  { questionText: "Which club won the first UEFA Cup/Europa League?", optionA: "Liverpool", optionB: "Tottenham", optionC: "Juventus", correctAnswer: "B", difficulty: "hard" },
  { questionText: "How many goals did Thierry Henry score for Arsenal in total?", optionA: "175", optionB: "228", optionC: "189", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Who holds the record for fastest hat-trick in Premier League history?", optionA: "Robbie Fowler", optionB: "Sadio Mane", optionC: "Kun Aguero", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Which goalkeeper scored a goal in the Premier League?", optionA: "Alisson", optionB: "Ederson", optionC: "Tim Howard", correctAnswer: "A", difficulty: "medium" },
  { questionText: "How many seasons has the Premier League been running?", optionA: "Over 25", optionB: "Over 30", optionC: "Over 20", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Which team has the longest unbeaten Premier League run?", optionA: "Chelsea", optionB: "Arsenal", optionC: "Manchester City", correctAnswer: "B", difficulty: "easy" },
  { questionText: "Who scored the first ever Premier League goal?", optionA: "Alan Shearer", optionB: "Brian Deane", optionC: "Teddy Sheringham", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which club has been relegated from the Premier League the most times?", optionA: "Sunderland", optionB: "Norwich City", optionC: "West Brom", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Who was the first African to score a Premier League hat-trick?", optionA: "Didier Drogba", optionB: "Tony Yeboah", optionC: "Yakubu", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which club has won the most FA Cups?", optionA: "Manchester United", optionB: "Arsenal", optionC: "Chelsea", correctAnswer: "B", difficulty: "medium" },
  { questionText: "How many FA Cups has Arsenal won?", optionA: "12", optionB: "14", optionC: "10", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Who scored the winning goal in the 2017 FA Cup final?", optionA: "Alexis Sanchez", optionB: "Aaron Ramsey", optionC: "Olivier Giroud", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which team has the most League Cup wins?", optionA: "Liverpool", optionB: "Manchester City", optionC: "Aston Villa", correctAnswer: "A", difficulty: "medium" },
  { questionText: "How many League Cups has Liverpool won?", optionA: "7", optionB: "9", optionC: "8", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Who is the top scorer in World Cup qualifying history?", optionA: "Cristiano Ronaldo", optionB: "Ali Daei", optionC: "Lionel Messi", correctAnswer: "A", difficulty: "hard" },
  { questionText: "Which country has won the Copa America the most times?", optionA: "Brazil", optionB: "Argentina", optionC: "Uruguay", correctAnswer: "B", difficulty: "medium" },
  { questionText: "How many Copa Americas has Argentina won?", optionA: "13", optionB: "15", optionC: "16", correctAnswer: "C", difficulty: "hard" },
  { questionText: "Who won the Copa America 2021?", optionA: "Brazil", optionB: "Argentina", optionC: "Colombia", correctAnswer: "B", difficulty: "easy" },
  { questionText: "Which player has won the most Copa America titles?", optionA: "Lionel Messi", optionB: "Pele", optionC: "Diego Maradona", correctAnswer: "A", difficulty: "hard" },
  { questionText: "Who won the first ever Copa America?", optionA: "Brazil", optionB: "Uruguay", optionC: "Argentina", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which European player has scored the most international goals?", optionA: "Miroslav Klose", optionB: "Cristiano Ronaldo", optionC: "Robert Lewandowski", correctAnswer: "B", difficulty: "easy" },
  { questionText: "How many international goals does Cristiano Ronaldo have?", optionA: "Over 100", optionB: "Over 120", optionC: "Over 130", correctAnswer: "C", difficulty: "medium" },
  { questionText: "Who is Portugal's most capped player?", optionA: "Luis Figo", optionB: "Cristiano Ronaldo", optionC: "Pepe", correctAnswer: "B", difficulty: "easy" },
  { questionText: "Which player has played in the most World Cups?", optionA: "Lionel Messi", optionB: "Lothar Matthaus", optionC: "Cristiano Ronaldo", correctAnswer: "A", difficulty: "hard" },
  { questionText: "How many World Cups has Messi played in?", optionA: "4", optionB: "5", optionC: "3", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Which World Cup had the fewest goals scored?", optionA: "Italy 1990", optionB: "USA 1994", optionC: "Germany 2006", correctAnswer: "A", difficulty: "hard" },
  { questionText: "What was the average goals per game in the 1990 World Cup?", optionA: "2.21", optionB: "2.52", optionC: "2.00", correctAnswer: "A", difficulty: "hard" },
  { questionText: "Which stadium has the largest capacity in England?", optionA: "Old Trafford", optionB: "Wembley", optionC: "Tottenham Stadium", correctAnswer: "B", difficulty: "easy" },
  { questionText: "What is the capacity of Wembley Stadium?", optionA: "80,000", optionB: "90,000", optionC: "100,000", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Which club plays at the Allianz Arena?", optionA: "Borussia Dortmund", optionB: "Bayern Munich", optionC: "Schalke", correctAnswer: "B", difficulty: "easy" },
  { questionText: "What is the capacity of the Allianz Arena?", optionA: "70,000", optionB: "75,000", optionC: "65,000", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which country hosted the 2020 European Championship?", optionA: "England", optionB: "Multiple countries", optionC: "Germany", correctAnswer: "B", difficulty: "easy" },
  { questionText: "Who won Euro 2020?", optionA: "England", optionB: "Italy", optionC: "Spain", correctAnswer: "B", difficulty: "easy" },
  { questionText: "Who scored the winning penalty in the Euro 2020 final?", optionA: "Jorginho", optionB: "Leonardo Bonucci", optionC: "It was a shootout", correctAnswer: "C", difficulty: "hard" },
  { questionText: "Which player missed the decisive penalty in Euro 2020 final?", optionA: "Marcus Rashford", optionB: "Bukayo Saka", optionC: "Jadon Sancho", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Who won Euro 2016?", optionA: "France", optionB: "Portugal", optionC: "Germany", correctAnswer: "B", difficulty: "easy" },
  { questionText: "Who scored the winning goal in the Euro 2016 final?", optionA: "Cristiano Ronaldo", optionB: "Nani", optionC: "Eder", correctAnswer: "C", difficulty: "medium" },
  { questionText: "Which country has won the most European Championships?", optionA: "Germany", optionB: "Spain", optionC: "Germany and Spain tied", correctAnswer: "C", difficulty: "medium" },
  { questionText: "How many European Championships have Spain won?", optionA: "2", optionB: "3", optionC: "4", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Who is Spain's all-time top scorer?", optionA: "Raul", optionB: "David Villa", optionC: "Fernando Torres", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Which club did David Villa never play for?", optionA: "Barcelona", optionB: "Valencia", optionC: "Real Madrid", correctAnswer: "C", difficulty: "medium" },
  { questionText: "Who is France's all-time top scorer?", optionA: "Thierry Henry", optionB: "Michel Platini", optionC: "Olivier Giroud", correctAnswer: "C", difficulty: "medium" },
  { questionText: "How many goals has Olivier Giroud scored for France?", optionA: "Over 50", optionB: "Over 40", optionC: "Over 60", correctAnswer: "A", difficulty: "hard" },
  { questionText: "Which club did Zinedine Zidane manage first?", optionA: "Real Madrid B", optionB: "Real Madrid", optionC: "Marseille", correctAnswer: "A", difficulty: "medium" },
  { questionText: "How many Champions League titles did Zidane win as manager?", optionA: "2", optionB: "3", optionC: "4", correctAnswer: "B", difficulty: "easy" },
  { questionText: "Who replaced Zinedine Zidane at Real Madrid in 2021?", optionA: "Carlo Ancelotti", optionB: "Julen Lopetegui", optionC: "Santiago Solari", correctAnswer: "A", difficulty: "medium" },
  { questionText: "Which player has won the most Champions League titles?", optionA: "Cristiano Ronaldo", optionB: "Paco Gento", optionC: "Paolo Maldini", correctAnswer: "B", difficulty: "hard" },
  { questionText: "How many Champions League titles did Paco Gento win?", optionA: "5", optionB: "6", optionC: "7", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which club did Gento play for his entire career?", optionA: "Barcelona", optionB: "Real Madrid", optionC: "Atletico Madrid", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Who is the youngest player to score in the Champions League?", optionA: "Kylian Mbappe", optionB: "Ansu Fati", optionC: "Celestine Babayaro", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Who is the oldest player to score in the Champions League?", optionA: "Francesco Totti", optionB: "Ryan Giggs", optionC: "Zlatan Ibrahimovic", correctAnswer: "A", difficulty: "hard" },
  { questionText: "Which team has played in the most Champions League finals?", optionA: "Bayern Munich", optionB: "Real Madrid", optionC: "AC Milan", correctAnswer: "B", difficulty: "medium" },
  { questionText: "How many Champions League finals has Real Madrid played?", optionA: "15", optionB: "17", optionC: "19", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which English team has played in the most Champions League finals?", optionA: "Manchester United", optionB: "Liverpool", optionC: "Chelsea", correctAnswer: "B", difficulty: "medium" },
  { questionText: "How many Champions League finals has Liverpool played?", optionA: "7", optionB: "9", optionC: "6", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Who scored Liverpool's goals in the 2019 Champions League final?", optionA: "Mohamed Salah", optionB: "Salah and Origi", optionC: "Sadio Mane", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Which manager has managed in the most Champions League finals?", optionA: "Jose Mourinho", optionB: "Carlo Ancelotti", optionC: "Alex Ferguson", correctAnswer: "B", difficulty: "hard" },
  { questionText: "How many Champions League finals has Carlo Ancelotti managed?", optionA: "5", optionB: "6", optionC: "4", correctAnswer: "A", difficulty: "hard" },
  { questionText: "Which stadium hosted the 2023 Champions League final?", optionA: "Ataturk Olympic Stadium", optionB: "Wembley", optionC: "Parc des Princes", correctAnswer: "A", difficulty: "medium" },
  { questionText: "Who scored in the 2023 Champions League final?", optionA: "Erling Haaland", optionB: "Rodri", optionC: "Kevin De Bruyne", correctAnswer: "B", difficulty: "medium" },
  { questionText: "What was the score in the 2023 Champions League final?", optionA: "1-0", optionB: "2-0", optionC: "2-1", correctAnswer: "A", difficulty: "easy" },
  { questionText: "Which team lost the 2023 Champions League final?", optionA: "AC Milan", optionB: "Inter Milan", optionC: "Napoli", correctAnswer: "B", difficulty: "easy" },
  { questionText: "Who was the Man of the Match in the 2023 Champions League final?", optionA: "Erling Haaland", optionB: "Rodri", optionC: "Ederson", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Which manager won the 2023 Champions League?", optionA: "Simone Inzaghi", optionB: "Pep Guardiola", optionC: "Jurgen Klopp", correctAnswer: "B", difficulty: "easy" },
  { questionText: "How many Champions League titles has Pep Guardiola won?", optionA: "2", optionB: "3", optionC: "4", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Which clubs has Pep Guardiola won the Champions League with?", optionA: "Barcelona only", optionB: "Barcelona and Man City", optionC: "Barcelona, Bayern and Man City", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Who is the top scorer in Serie A history?", optionA: "Francesco Totti", optionB: "Silvio Piola", optionC: "Giuseppe Meazza", correctAnswer: "B", difficulty: "hard" },
  { questionText: "How many goals did Silvio Piola score in Serie A?", optionA: "274", optionB: "290", optionC: "310", correctAnswer: "A", difficulty: "hard" },
  { questionText: "Which team has won the most Serie A titles?", optionA: "AC Milan", optionB: "Inter Milan", optionC: "Juventus", correctAnswer: "C", difficulty: "easy" },
  { questionText: "How many Serie A titles has Juventus won?", optionA: "34", optionB: "36", optionC: "38", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which club won Serie A in 2022-23?", optionA: "Inter Milan", optionB: "Napoli", optionC: "AC Milan", correctAnswer: "B", difficulty: "easy" },
  { questionText: "How many points did Napoli finish with in 2022-23 Serie A?", optionA: "86", optionB: "90", optionC: "95", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Who was Napoli's top scorer in 2022-23?", optionA: "Khvicha Kvaratskhelia", optionB: "Victor Osimhen", optionC: "Giacomo Raspadori", correctAnswer: "B", difficulty: "easy" },
  { questionText: "How many goals did Victor Osimhen score in 2022-23 Serie A?", optionA: "21", optionB: "26", optionC: "31", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Which Nigerian has scored the most Serie A goals?", optionA: "Victor Osimhen", optionB: "Obafemi Martins", optionC: "Taribo West", correctAnswer: "A", difficulty: "medium" },
  { questionText: "Which club did Obafemi Martins play for in Italy?", optionA: "AC Milan", optionB: "Inter Milan", optionC: "Juventus", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Who is the top scorer in Ligue 1 history?", optionA: "Zlatan Ibrahimovic", optionB: "Delio Onnis", optionC: "Jean-Pierre Papin", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which club has won the most Ligue 1 titles?", optionA: "Marseille", optionB: "PSG", optionC: "Saint-Etienne", correctAnswer: "C", difficulty: "hard" },
  { questionText: "How many Ligue 1 titles has Saint-Etienne won?", optionA: "8", optionB: "10", optionC: "12", correctAnswer: "B", difficulty: "hard" },
  { questionText: "How many consecutive Ligue 1 titles has PSG won?", optionA: "8", optionB: "10", optionC: "6", correctAnswer: "A", difficulty: "hard" },
  { questionText: "Who is PSG's all-time top scorer?", optionA: "Zlatan Ibrahimovic", optionB: "Edinson Cavani", optionC: "Kylian Mbappe", correctAnswer: "B", difficulty: "medium" },
  { questionText: "How many goals did Cavani score for PSG?", optionA: "180", optionB: "200", optionC: "220", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which African player has scored the most goals for PSG?", optionA: "Moussa Dembele", optionB: "Achraf Hakimi", optionC: "None over 50", correctAnswer: "C", difficulty: "hard" },
  { questionText: "Who won the Bundesliga Golden Boot in 2022-23?", optionA: "Erling Haaland", optionB: "Christopher Nkunku", optionC: "Serge Gnabry", correctAnswer: "B", difficulty: "medium" },
  { questionText: "How many goals did Lewandowski score in his final Bundesliga season?", optionA: "30", optionB: "35", optionC: "40", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which team won the DFB-Pokal in 2022-23?", optionA: "Bayern Munich", optionB: "RB Leipzig", optionC: "Freiburg", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Who is Borussia Dortmund's all-time top scorer?", optionA: "Robert Lewandowski", optionB: "Michael Zorc", optionC: "Marco Reus", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which English player has played for Borussia Dortmund?", optionA: "Phil Foden", optionB: "Jude Bellingham", optionC: "Bukayo Saka", correctAnswer: "B", difficulty: "easy" },
  { questionText: "How many goals did Jude Bellingham score for Dortmund?", optionA: "14", optionB: "22", optionC: "18", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which club did Jude Bellingham join in 2023?", optionA: "Manchester City", optionB: "Real Madrid", optionC: "Liverpool", correctAnswer: "B", difficulty: "easy" },
  { questionText: "What was Bellingham's transfer fee to Real Madrid?", optionA: "88 million euros", optionB: "103 million euros", optionC: "120 million euros", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Who is the most expensive English player in history?", optionA: "Jack Grealish", optionB: "Jude Bellingham", optionC: "Harry Maguire", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Which African country hosted the 2019 AFCON?", optionA: "Cameroon", optionB: "Egypt", optionC: "Morocco", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Who won the 2019 AFCON?", optionA: "Senegal", optionB: "Algeria", optionC: "Nigeria", correctAnswer: "B", difficulty: "easy" },
  { questionText: "Who scored the only goal in the 2019 AFCON final?", optionA: "Riyad Mahrez", optionB: "Baghdad Bounedjah", optionC: "Islam Slimani", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which Nigeria player was top scorer at 2019 AFCON?", optionA: "Victor Osimhen", optionB: "Odion Ighalo", optionC: "Ahmed Musa", correctAnswer: "B", difficulty: "medium" },
  { questionText: "How many goals did Odion Ighalo score at 2019 AFCON?", optionA: "3", optionB: "5", optionC: "7", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which tournament did Nigeria finish third at in 2019?", optionA: "World Cup", optionB: "AFCON", optionC: "WAFU Cup", correctAnswer: "B", difficulty: "easy" },
  { questionText: "Who is Nigeria's current highest paid player?", optionA: "Victor Osimhen", optionB: "Samuel Chukwueze", optionC: "Wilfred Ndidi", correctAnswer: "A", difficulty: "easy" },
  { questionText: "Which club does Samuel Chukwueze play for?", optionA: "Napoli", optionB: "AC Milan", optionC: "Villarreal", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Which Nigerian played for AC Milan, Inter and Juventus?", optionA: "Taribo West", optionB: "Obafemi Martins", optionC: "None", correctAnswer: "C", difficulty: "hard" },
  { questionText: "Who holds the record for most consecutive wins in top 5 leagues?", optionA: "Real Madrid", optionB: "Bayern Munich", optionC: "Manchester City", correctAnswer: "B", difficulty: "hard" },
  { questionText: "How many consecutive wins did Bayern Munich achieve?", optionA: "19", optionB: "23", optionC: "21", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which team has the most consecutive home wins in Premier League?", optionA: "Chelsea", optionB: "Manchester City", optionC: "Liverpool", correctAnswer: "C", difficulty: "hard" },
  { questionText: "What is the record for most goals in a single Premier League game?", optionA: "9", optionB: "11", optionC: "10", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which match holds the Premier League goal record?", optionA: "Portsmouth vs Reading", optionB: "Man Utd vs Southampton", optionC: "Tottenham vs Wigan", correctAnswer: "A", difficulty: "hard" },
  { questionText: "What was the score in the record-breaking Premier League match?", optionA: "7-4", optionB: "9-3", optionC: "8-3", correctAnswer: "A", difficulty: "hard" },
  { questionText: "Who scored the fastest Premier League goal from kick-off?", optionA: "Ledley King", optionB: "Shane Long", optionC: "Christian Eriksen", correctAnswer: "B", difficulty: "hard" },
  { questionText: "How fast was the fastest Premier League goal?", optionA: "7.69 seconds", optionB: "9.9 seconds", optionC: "12 seconds", correctAnswer: "A", difficulty: "hard" },
  { questionText: "Which player holds the record for most yellow cards in Premier League?", optionA: "Lee Bowyer", optionB: "Gareth Barry", optionC: "Kevin Davies", correctAnswer: "B", difficulty: "hard" },
  { questionText: "How many yellow cards does Gareth Barry have in the Premier League?", optionA: "110", optionB: "123", optionC: "135", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Who holds the record for most red cards in Premier League?", optionA: "Patrick Vieira", optionB: "Roy Keane", optionC: "Duncan Ferguson", correctAnswer: "B", difficulty: "hard" },
  { questionText: "How many red cards did Roy Keane receive in the Premier League?", optionA: "6", optionB: "8", optionC: "10", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which team has received the most red cards in Premier League history?", optionA: "Arsenal", optionB: "Everton", optionC: "Newcastle", correctAnswer: "B", difficulty: "hard" },
  { questionText: "What is the record for most penalties scored in a Premier League season?", optionA: "10", optionB: "12", optionC: "14", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Who scored the most penalties in a single Premier League season?", optionA: "Frank Lampard", optionB: "Steven Gerrard", optionC: "Mo Salah", correctAnswer: "A", difficulty: "hard" },
  { questionText: "Which goalkeeper has saved the most penalties in Premier League history?", optionA: "David Seaman", optionB: "David James", optionC: "Petr Cech", correctAnswer: "A", difficulty: "hard" },
  { questionText: "How many penalties has David Seaman saved in the Premier League?", optionA: "11", optionB: "13", optionC: "15", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Who is the Premier League's most expensive goalkeeper ever?", optionA: "Alisson", optionB: "Kepa", optionC: "Ederson", correctAnswer: "B", difficulty: "medium" },
  { questionText: "How much did Chelsea pay for Kepa?", optionA: "65 million", optionB: "72 million", optionC: "80 million", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which Nigerian goalkeeper has made the most Premier League appearances?", optionA: "Vincent Enyeama", optionB: "Carl Ikeme", optionC: "Neither played in EPL", correctAnswer: "C", difficulty: "hard" },
  { questionText: "Which sport uses a puck?", optionA: "Field Hockey", optionB: "Ice Hockey", optionC: "Lacrosse", correctAnswer: "B", difficulty: "easy" },
  { questionText: "How many players are in a volleyball team on court?", optionA: "5", optionB: "6", optionC: "7", correctAnswer: "B", difficulty: "easy" },
  { questionText: "What is the diameter of a basketball hoop?", optionA: "18 inches", optionB: "15 inches", optionC: "20 inches", correctAnswer: "A", difficulty: "hard" },
  { questionText: "How long is a standard tennis court?", optionA: "78 feet", optionB: "84 feet", optionC: "72 feet", correctAnswer: "A", difficulty: "hard" },
  { questionText: "What is the length of a cricket bat?", optionA: "36 inches max", optionB: "38 inches max", optionC: "40 inches max", correctAnswer: "B", difficulty: "hard" },
  { questionText: "How heavy is a men's shot put?", optionA: "7.26 kg", optionB: "6 kg", optionC: "8 kg", correctAnswer: "A", difficulty: "hard" },
  { questionText: "What is the weight of a women's discus?", optionA: "1 kg", optionB: "2 kg", optionC: "1.5 kg", correctAnswer: "A", difficulty: "hard" },
  { questionText: "How long is an Olympic hammer throw cable?", optionA: "1.175-1.215m", optionB: "1.5m", optionC: "2m", correctAnswer: "A", difficulty: "hard" },
  { questionText: "What is the length of an Olympic javelin for men?", optionA: "2.6-2.7m", optionB: "2.2-2.4m", optionC: "2.8-3.0m", correctAnswer: "A", difficulty: "hard" },
  { questionText: "How high is a men's high jump bar at world record?", optionA: "2.45m", optionB: "2.35m", optionC: "2.50m", correctAnswer: "A", difficulty: "hard" },
  { questionText: "What is the men's pole vault world record?", optionA: "6.15m", optionB: "6.21m", optionC: "6.00m", correctAnswer: "B", difficulty: "hard" },
  { questionText: "How far is the men's long jump world record?", optionA: "8.90m", optionB: "8.95m", optionC: "9.00m", correctAnswer: "B", difficulty: "hard" },
  { questionText: "What is the men's triple jump world record?", optionA: "18.29m", optionB: "17.98m", optionC: "18.50m", correctAnswer: "A", difficulty: "hard" },
  { questionText: "Who holds the men's triple jump world record?", optionA: "Christian Taylor", optionB: "Jonathan Edwards", optionC: "Kenny Harrison", correctAnswer: "B", difficulty: "hard" },
  { questionText: "What is the men's 400m world record?", optionA: "43.03 seconds", optionB: "43.45 seconds", optionC: "43.18 seconds", correctAnswer: "A", difficulty: "hard" },
  { questionText: "Who holds the men's 400m world record?", optionA: "Michael Johnson", optionB: "Wayde van Niekerk", optionC: "LaShawn Merritt", correctAnswer: "B", difficulty: "medium" },
  { questionText: "What is the men's 800m world record?", optionA: "1:40.91", optionB: "1:41.50", optionC: "1:42.00", correctAnswer: "A", difficulty: "hard" },
  { questionText: "Who holds the men's 800m world record?", optionA: "Wilson Kipketer", optionB: "David Rudisha", optionC: "Emmanuel Korir", correctAnswer: "B", difficulty: "medium" },
  { questionText: "What is the men's 1500m world record?", optionA: "3:26.00", optionB: "3:28.00", optionC: "3:30.00", correctAnswer: "A", difficulty: "hard" },
  { questionText: "Who holds the men's 1500m world record?", optionA: "Hicham El Guerrouj", optionB: "Jakob Ingebrigtsen", optionC: "Timothy Cheruiyot", correctAnswer: "A", difficulty: "medium" },
  { questionText: "What country is Hicham El Guerrouj from?", optionA: "Kenya", optionB: "Morocco", optionC: "Ethiopia", correctAnswer: "B", difficulty: "medium" },
  { questionText: "What is the marathon world record?", optionA: "2:01:09", optionB: "2:00:35", optionC: "2:02:57", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Who holds the marathon world record?", optionA: "Eliud Kipchoge", optionB: "Kelvin Kiptum", optionC: "Kenenisa Bekele", correctAnswer: "B", difficulty: "medium" },
  { questionText: "Which country dominates long distance running?", optionA: "Ethiopia", optionB: "Kenya", optionC: "Both equally", correctAnswer: "B", difficulty: "medium" },
  { questionText: "What is the 100m hurdles world record for women?", optionA: "12.12 seconds", optionB: "12.20 seconds", optionC: "12.25 seconds", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Who holds the women's 100m hurdles world record?", optionA: "Kendra Harrison", optionB: "Tobi Amusan", optionC: "Jasmine Camacho-Quinn", correctAnswer: "B", difficulty: "medium" },
  { questionText: "What country is Tobi Amusan from?", optionA: "USA", optionB: "Jamaica", optionC: "Nigeria", correctAnswer: "C", difficulty: "easy" },
  { questionText: "Which Nigerian became World Champion in athletics?", optionA: "Blessing Okagbare", optionB: "Tobi Amusan", optionC: "Mary Onyali", correctAnswer: "B", difficulty: "medium" },
  { questionText: "What event did Tobi Amusan win World Championship in?", optionA: "100m", optionB: "100m hurdles", optionC: "200m", correctAnswer: "B", difficulty: "easy" },
  { questionText: "Which Nigerian won Olympic gold in the long jump?", optionA: "Blessing Okagbare", optionB: "Chioma Ajunwa", optionC: "Mary Onyali", correctAnswer: "B", difficulty: "medium" },
  { questionText: "In which Olympics did Chioma Ajunwa win gold?", optionA: "1992 Barcelona", optionB: "1996 Atlanta", optionC: "2000 Sydney", correctAnswer: "B", difficulty: "medium" },
  { questionText: "What event did Chioma Ajunwa win?", optionA: "100m", optionB: "Long Jump", optionC: "High Jump", correctAnswer: "B", difficulty: "easy" },
  { questionText: "Who is Nigeria's most successful Olympian?", optionA: "Chioma Ajunwa", optionB: "Mary Onyali", optionC: "Dream Team 96", correctAnswer: "A", difficulty: "medium" },
  { questionText: "Which sport has Nigeria won the most Olympic medals in?", optionA: "Athletics", optionB: "Football", optionC: "Wrestling", correctAnswer: "A", difficulty: "medium" },
  { questionText: "How many Olympic gold medals has Nigeria won in total?", optionA: "2", optionB: "3", optionC: "4", correctAnswer: "B", difficulty: "hard" },
  { questionText: "Which Nigerian weightlifter won Olympic silver?", optionA: "Mariam Usman", optionB: "Rilwan Oluwafemi", optionC: "Rafiatu Lawal", correctAnswer: "A", difficulty: "hard" },
];

async function seedExtraQuestions() {
  console.log("Starting to seed extra questions...");
  console.log(`Questions to insert: ${extraQuestions.length}`);
  
  let insertedCount = 0;
  const batchSize = 50;
  
  for (let i = 0; i < extraQuestions.length; i += batchSize) {
    const batch = extraQuestions.slice(i, i + batchSize);
    try {
      await db.insert(questions).values(batch);
      insertedCount += batch.length;
      console.log(`Inserted ${insertedCount} questions...`);
    } catch (error) {
      console.log(`Error in batch, continuing...`);
    }
  }
  
  console.log(`\nExtra seeding complete! ${insertedCount} questions inserted.`);
  
  process.exit(0);
}

seedExtraQuestions().catch((error) => {
  console.error("Error seeding questions:", error);
  process.exit(1);
});
